# Generated by Django 2.1.2 on 2018-10-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('city', models.CharField(max_length=75, verbose_name='city')),
                ('state_or_province', models.CharField(max_length=2, verbose_name='state, province')),
                ('postal_code', models.CharField(max_length=15, verbose_name='postal code')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=100, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="owner's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="owner's last name")),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit')], default='Dog', max_length=20, verbose_name="pet's species")),
                ('name', models.CharField(max_length=30, verbose_name="pet's name")),
                ('breed', models.CharField(max_length=30, verbose_name="pet's breed (For Dogs: black lab, poodle, etc.)")),
                ('age', models.FloatField(verbose_name="pet's age (6 months would be 0.5)")),
                ('weight', models.FloatField(verbose_name="pet's weight")),
                ('owner', models.ForeignKey(help_text="pet's owner", on_delete=django.db.models.deletion.PROTECT, to='backend.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(help_text="pet's owner", on_delete=django.db.models.deletion.PROTECT, to='backend.Owner'),
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(help_text="pet's owner", on_delete=django.db.models.deletion.PROTECT, to='backend.Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state_or_province', 'postal_code')},
        ),
    ]
